### ISSUE TITLE
capstone.CsError: Invalid option (CS_ERR_OPTION)

### ISSUE THREAD

**Issue by Lein-Zhang** [HexHive/retrowrite#52]
i can't run it .

`( retro) root:#cd retrowrite/demos/user_demo

( retro) root:retrowrite/demos/user_demo# make 

( retro) root:retrowrite/demos/user_demo# retrowrite  --asan heap heap_retwo

Traceback (most recent call last):
  File "/home/zhang/retrowrite/retro/bin/retrowrite", line 137, in <module>
    loader.load_data_sections(slist, lambda x: x in Rewriter.DATASECTIONS)
  File "/home/zhang/retrowrite/librw/loader.py", line 69, in load_data_sections
    disasm_bytes(section.data(), seclist[sec]['base']))
  File "/home/zhang/retrowrite/librw/disasm.py", line 6, in disasm_bytes
    md.syntax = CS_OPT_SYNTAX_ATT
  File "/home/zhang/retrowrite/retro/lib/python3.6/site-packages/capstone/__init__.py", line 1012, in syntax
    raise CsError(status)
capstone.CsError: Invalid option (CS_ERR_OPTION)`

**Comment by cyanpencil** [comment]
Thanks for reporting! Should be fixed now from #ef4e541
